spring:
 datasource:
   url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
   username: ${DATABASE_USERNAME}
   password: ${DATABASE_PASSWORD}
   driver-class-name: org.postgresql.Driver
 flyway:
   baseline-on-migrate: true

rsa:
 private-key: classpath:certs/private.pem
 public-key: classpath:certs/public.pem

logging:
  level:
    org.flywaydb: DEBUG

