spring:
 datasource:
   url: jdbc:postgresql://localhost:5331/prontuario
   username: postgres
   password: password
   driver-class-name: org.postgresql.Driver
 flyway:
   baseline-on-migrate: true
 jpa:
   hibernate:
     ddl-auto: validate
   show-sql: true
   generate-ddl: true

rsa:
 private-key: classpath:certs/private.pem
 public-key: classpath:certs/public.pem

logging:
  level:
    org.flywaydb: DEBUG

