name: CI/CD - Build Backend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: prontuario
        ports:
          - 5331:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'maven'
      - name: login docker repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Add executable permissions to mvnw
        run: |
          chmod +x ./mvnw
      - name: Build and run Test with maven
        run: ./mvnw -ntp -B verify jib:build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Render
        run: |
          curl --request POST \
               --url 'https://api.render.com/v1/deploys' \
               --header 'Content-Type: application/json' \
               --header 'Authorization: Bearer ${{ secrets.MY_RENDER_API_TOKEN }}' \
               --data '{
                 "serviceId": "${{ secrets.MY_RENDER_SERVICE_ID }}",
                 "build": {
                   "buildCommand": "",
                   "directory": "target"
                 }
               }'
          sleep 30