name: CI/CD - Build Backend

on:
  workflow_dispatch:
  push:
    branches: #agr qualquer branch dispara as actions, mas o deploy em render so pega a branch main.
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: prontuario
        ports:
          - 5331:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'maven'
      - name: login docker repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Add executable permissions to mvnw
        run: |
          chmod +x ./mvnw
      - name: Build and run Test with maven
        run: ./mvnw -ntp -B verify jib:build
  pull-request:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        branch: main
        title: pre-deploy
        token: ${{ secrets.MY_GITHUB_TOKEN }}

